import { VideoCardProps } from "@/components/VideoCard";
const sampleVideos:VideoCardProps[] = [
  {
    id: "1",
    thumbnail: "/assets/samples/thumbnail (1).png",
    createdAt: new Date("2025-05-01 06:25:54.437"),
    userImage: "/assets/images/jason.png",
    views: 10,
    visibility: "public",
    duration: 156,
    title: "Sample Video 1",
    username: "Yash Panwar",
  },
  {
    id: "2",
    thumbnail: "/assets/samples/thumbnail (2).png",
    createdAt: new Date("2025-04-21 10:15:20.100"),
    userImage: "/assets/images/jason.png",
    views: 245,
    visibility: "private",
    duration: 320,
    title: "Building with Next.js 14",
    username: "Aarav Mehta",
  },
  {
    id: "3",
    thumbnail: "/assets/samples/thumbnail (3).png",
    createdAt: new Date("2025-03-12 08:45:12.000"),
    userImage: "/assets/images/jason.png",
    views: 89,
    visibility: "public",
    duration: 95,
    title: "React Server Components Explained",
    username: "Riya Sharma",
  },
  {
    id: "4",
    thumbnail: "/assets/samples/thumbnail (4).png",
    createdAt: new Date("2025-02-05 14:30:00.000"),
    userImage: "/assets/images/jason.png",
    views: 1204,
    visibility: "public",
    duration: 540,
    title: "Full Stack App Walkthrough",
    username: "Dev Patel",
  },
  {
    id: "5",
    thumbnail: "/assets/samples/thumbnail (5).png",
    createdAt: new Date("2025-01-18 18:10:44.000"),
    userImage: "/assets/images/jason.png",
    views: 543,
    visibility: "private",
    duration: 210,
    title: "Mastering Tailwind CSS",
    username: "Ananya Singh",
  },
  {
    id: "6",
    thumbnail: "/assets/samples/thumbnail (6).png",
    createdAt: new Date("2024-12-22 09:00:00.000"),
    userImage: "/assets/images/jason.png",
    views: 3200,
    visibility: "public",
    duration: 780,
    title: "Authentication in Next.js",
    username: "Kabir Verma",
  },
  {
    id: "7",
    thumbnail: "/assets/samples/thumbnail (7).png",
    createdAt: new Date("2024-11-11 11:11:11.000"),
    userImage: "/assets/images/jason.png",
    views: 76,
    visibility: "public",
    duration: 134,
    title: "Deploying to Vercel Like a Pro",
    username: "Sneha Kapoor",
  },
  {
    id: "8",
    thumbnail: "/assets/samples/thumbnail (8).png",
    createdAt: new Date("2024-10-01 07:45:30.000"),
    userImage: "/assets/images/jason.png",
    views: 9876,
    visibility: "public",
    duration: 1020,
    title: "Scaling Your Full Stack App",
    username: "Arjun Rao",
  },
];
export default sampleVideos;